[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[dependency-groups]
dev = [
    "ipython==8.10.0",
    "jupyter>=1.0.0,<2",
    "mypy==0.991",
    "pre-commit==3.2.0",
    "pylint==2.15.10",
    "pytest==7.4.4",
    "pytest-mock==3.11.1",
    "ruff==0.11.11",
    "black[jupyter]<=23.9.1,>=23.7.0",
    "codespell[toml]>=v2.2.6",
    "pytest-cov>=6.1.1",
]

[project]
name = "llama-index-llms-duel"
version = "0.1.0"
description = "llama-index llms duel agents integration"
authors = [{ name = "Aaron Shaw" }]
requires-python = ">=3.10,<4.0"
readme = "README.md"
license = "MIT"
keywords = ["duel", "duel-agents", "model-routing", "openai", "router"]
dependencies = [
    "llama-index-llms-openai-like>=0.5.0,<0.6",
    "llama-index-core>=0.13.0,<0.15",
]

[project.urls]
Homepage = "https://duelagents.com"
Repository = "https://github.com/2aronS/Duel-Agents"

[tool.codespell]
check-filenames = true
check-hidden = true
skip = "*.csv,*.html,*.json,*.jsonl,*.pdf,*.txt,*.ipynb"

[tool.hatch.build.targets.sdist]
include = ["llama_index/"]
exclude = ["**/BUILD"]

[tool.hatch.build.targets.wheel]
include = ["llama_index/"]
exclude = ["**/BUILD"]

[tool.llamahub]
contains_example = false
import_path = "llama_index.llms.duel"

[tool.llamahub.class_authors]
DuelLLM = "2aronS"

[tool.mypy]
disallow_untyped_defs = true
exclude = ["_static", "build", "examples", "notebooks", "venv"]
ignore_missing_imports = true
python_version = "3.10"
